<?php

namespace App\Request\Merchant;

use Hyperf\Validation\Request\FormRequest;

class ItemsRequest extends FormRequest
{

    use BaseMerchant;

    public function rules(): array
    {
        return [
            'name' => 'required|string',
            'category_id' => 'required|string',
            'brand_id' => 'string',
            'description' => 'string',
            'images' => 'array',
            'sku' => 'array',
            'sku.*.name' => 'required|string',
            'sku.*.barcode' => 'string',
            'sku.*.base_sku_id' => 'string',
            'sku.*.conversion_to_base' => 'required|numeric',
        ];
    }


    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }


}